# filename: .github/workflows/scheduled_scan.yml

name: Daily Stock Scanner

on:
  # Schedule to run at 7:00 AM and 4:00 PM EST (11:00 and 20:00 UTC)
  # Note: This is EDT. During standard time (EST), this will be 12:00 and 21:00 UTC.
  # Consider using a single time or adjusting for DST if precision is critical.
  schedule:
    - cron: '0 11 * * *' # 7 AM EST is 11:00 UTC during Daylight Saving
    - cron: '0 20 * * *' # 4 PM EST is 20:00 UTC during Daylight Saving

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Use a specific version

      - name: Cache AI Model
        id: cache-model
        uses: actions/cache@v4
        with:
          path: generalized_stock_model.h5
          key: ${{ runner.os }}-stock-model

      - name: Abort if model is not trained
        if: steps.cache-model.outputs.cache-hit != 'true'
        run: |
          echo "Error: AI model not found in cache."
          echo "Please run the manual 'Train AI Model' workflow first to generate the model."
          exit 1
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy scikit-learn tensorflow matplotlib ta lxml requests

      - name: Run Stock Scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alpha.py scan
